### ISSUE TITLE
Add custom.css

### ISSUE THREAD

**Issue by itcrowd72** [itcrowd72/visually_impaired_theme#1]
Add file for custom.css

**Comment by itcrowd72** [comment]
Issue reopen. When module will be updated, custom.css will be remove by theme updater. Need move custom.css to "files" directory

**Comment by itcrowd72** [comment]
Issue reopen. Need review and tests

**Comment by itcrowd72** [comment]
@keha выложи скриншот исходного кода твоего сайта, где стили подключаются (кэширование нужно отключить для дебага)

**Comment by keha** [comment]
все кэширование отключил https://красгимнастика.рф

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML+RDFa 1.0//EN"
  "http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" version="XHTML+RDFa 1.0" dir="ltr"
  xmlns:content="http://purl.org/rss/1.0/modules/content/"
  xmlns:dc="http://purl.org/dc/terms/"
  xmlns:foaf="http://xmlns.com/foaf/0.1/"
  xmlns:og="http://ogp.me/ns#"
  xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
  xmlns:sioc="http://rdfs.org/sioc/ns#"
  xmlns:sioct="http://rdfs.org/sioc/types#"
  xmlns:skos="http://www.w3.org/2004/02/skos/core#"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema#">

<head profile="http://www.w3.org/1999/xhtml/vocab">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="Generator" content="Drupal 7 (http://drupal.org)" />
  <title>Краевая спортивная школа по художественной гимнастике</title>
  <style type="text/css" media="all">
@import url("https://красгимнастика.рф/modules/system/system.base.css?oygz5l");
@import url("https://красгимнастика.рф/modules/system/system.menus.css?oygz5l");
@import url("https://красгимнастика.рф/modules/system/system.messages.css?oygz5l");
@import url("https://красгимнастика.рф/modules/system/system.theme.css?oygz5l");
</style>
<style type="text/css" media="all">
@import url("https://красгимнастика.рф/sites/all/modules/jquery_update/replace/ui/themes/base/minified/jquery.ui.core.min.css?oygz5l");
@import url("https://красгимнастика.рф/sites/all/modules/jquery_update/replace/ui/themes/base/minified/jquery.ui.theme.min.css?oygz5l");
@import url("https://красгимнастика.рф/modules/overlay/overlay-parent.css?oygz5l");
@import url("https://красгимнастика.рф/modules/contextual/contextual.css?oygz5l");
</style>
<style type="text/css" media="all">
@import url("https://красгимнастика.рф/sites/all/modules/colorbox_node/colorbox_node.css?oygz5l");
@import url("https://красгимнастика.рф/sites/all/modules/date/date_api/date.css?oygz5l");
@import url("https://красгимнастика.рф/sites/all/modules/date/date_popup/themes/datepicker.1.7.css?oygz5l");
@import url("https://красгимнастика.рф/modules/field/theme/field.css?oygz5l");
@import url("https://красгимнастика.рф/modules/node/node.css?oygz5l");
@import url("https://красгимнастика.рф/modules/search/search.css?oygz5l");
@import url("https://красгимнастика.рф/modules/user/user.css?oygz5l");
@import url("https://красгимнастика.рф/sites/all/modules/visually_impaired_module/css/visually_impaired_module.css?oygz5l");
@import url("https://красгимнастика.рф/sites/all/modules/youtube/css/youtube.css?oygz5l");
@import url("https://красгимнастика.рф/sites/all/modules/views/css/views.css?oygz5l");
@import url("https://красгимнастика.рф/sites/all/modules/back_to_top/css/back_to_top.css?oygz5l");
@import url("https://красгимнастика.рф/sites/all/modules/ckeditor/css/ckeditor.css?oygz5l");
@import url("https://красгимнастика.рф/sites/all/modules/admin_menu/admin_menu.css?oygz5l");
@import url("https://красгимнастика.рф/sites/all/modules/admin_menu/admin_menu.uid1.css?oygz5l");
@import url("https://красгимнастика.рф/sites/all/modules/admin_menu/admin_menu_toolbar/admin_menu_toolbar.css?oygz5l");
@import url("https://красгимнастика.рф/modules/shortcut/shortcut.css?oygz5l");
</style>
<style type="text/css" media="all">
@import url("https://красгимнастика.рф/sites/all/modules/colorbox/styles/default/colorbox_style.css?oygz5l");
@import url("https://красгимнастика.рф/sites/all/modules/ctools/css/ctools.css?oygz5l");
@import url("https://красгимнастика.рф/sites/all/modules/custom_search/custom_search.css?oygz5l");
@import url("https://красгимнастика.рф/sites/all/libraries/nivo-slider/themes/default/default.css?oygz5l");
@import url("https://красгимнастика.рф/sites/all/libraries/nivo-slider/nivo-slider.css?oygz5l");
@import url("https://красгимнастика.рф/sites/all/themes/visually_impaired_theme/css/style.css?oygz5l");
@import url("https://красгимнастика.рф/sites/all/libraries/superfish/css/superfish.css?oygz5l");
@import url("https://красгимнастика.рф/sites/all/libraries/superfish/css/superfish-smallscreen.css?oygz5l");
@import url("https://красгимнастика.рф/sites/all/libraries/superfish/style/spring.css?oygz5l");
</style>

**Comment by itcrowd72** [comment]
Кэш очищал? Да, действительно файл не подключен. Но он создался автоматически?

**Comment by keha** [comment]
файл создался автоматически, но я его перезаписал своим
разве в этом может быть причина?

**Comment by keha** [comment]
кэш очищен

**Comment by keha** [comment]
и по прямой ссылке файл доступен https://xn--80aaakzbjfpk2anfo.xn--p1ai/sites/default/files/visually_impaired_theme/custom.css

**Comment by itcrowd72** [comment]
> файл создался автоматически, но я его перезаписал своим
> разве в этом может быть причина?

Точно нет. 

так, а в логах сайта или логах вебсервера есть что-нибудь связанное с custom.css?

**Comment by keha** [comment]
создал учетку админскую как в прошлый раз, можно самому посмотреть

**Comment by itcrowd72** [comment]
Сразу ещё один недочет всплыл. При использовании стандартного тулбара панель для слабовидящих смещается вниз. У тебя стоит другой тулбар и панель для слабовидящих перекрывает его

**Comment by keha** [comment]
да, есть такое
я просто открываю ссылку с тулбара в новой вкладке, чтобы тему Seven получить

**Comment by itcrowd72** [comment]
Создай issue по этому поводу, я исправлю. Думаю, много кто пользуется этим admin menu

**Comment by itcrowd72** [comment]
В логах сайта ничего нет. Можешь дать мне доступ на хостинг? Напиши в личку на д.ру

**Comment by keha** [comment]
ок

**Comment by itcrowd72** [comment]
Тут, на ГХ создай. На орге очень неудобно работать

**Comment by keha** [comment]
ок

**Comment by itcrowd72** [comment]
У владельца сайта был баг, что системная переменная **file_public_path** была пустая. После сохранения страницы **admin/config/media/file-system** переменная вернула значение и всё заработало

![bildschirmfoto vom 2017-10-27 15-03-18](https://user-images.githubusercontent.com/29428813/32099014-feddcd34-bb27-11e7-896b-1a1d1c8b3822.png)
