### ISSUE TITLE
not readable admin link view and edit in node

### ISSUE THREAD

**Issue by keha** [itcrowd72/visually_impaired_theme#10]
Не читаемы ссылки  ноды "просмотр" и при hover на ссылку "редактировать" (синий текст на темно-сером)

**Comment by itcrowd72** [comment]
Покажи скриншот

**Comment by keha** [comment]
[раз](http://i96.fastpic.ru/big/2017/1101/54/ef7fa6e036200617abb05e45e7b06554.jpg)
[два](http://i89.fastpic.ru/big/2017/1101/27/4bc8a702f0004e86e8498cf760b35c27.jpg)

**Comment by itcrowd72** [comment]
Убрал фон табов и ховер

![bildschirmfoto vom 2017-11-01 13-32-55](https://user-images.githubusercontent.com/29428813/32266429-3426b372-bf09-11e7-877f-1315d9efde1e.png)

**Comment by keha** [comment]
тоже вариант решения

**Comment by itcrowd72** [comment]
Можешь добавить код https://github.com/itcrowd72/visually_impaired_theme/commit/82aa1dbbe5fb4d22029277c49726031ba428b42e в style.css, потому что обнову на орге я выпущу чуть позже
