### ISSUE TITLE
class rtcenter for image not working

### ISSUE THREAD

**Issue by keha** [itcrowd72/visually_impaired_theme#11]
Класс для центрирования, используемый ckeditor не применим для картинок заключенных в тег p

**Comment by itcrowd72** [comment]
Пример можешь привести где эта проблема?

**Comment by keha** [comment]
http://центрнадежда.рф - зеленая картинка "Добро пожаловать"

**Comment by itcrowd72** [comment]
У тебя на этом сайте последняя версия стоит? У меня как-то неправильно тему переключает

**Comment by itcrowd72** [comment]
Попробуй под анонимом

**Comment by itcrowd72** [comment]
И потом меню не работает периодически, хотя ошибок в консоли нет

**Comment by itcrowd72** [comment]
На другом твоем сайте всё отлично работает

**Comment by keha** [comment]
попробую тогда обновить ckeditor

**Comment by keha** [comment]
он древний

**Comment by itcrowd72** [comment]
не-не-не, не трогай ckeditor. Или у тебя http://центрнадежда.рф нормально версию переключает? У меня на разных браузерах не работает

**Comment by keha** [comment]
у меня нормально переключает

**Comment by keha** [comment]
ты же нижний баннер используешь? потому что верхний это моё поделие

**Comment by itcrowd72** [comment]
У меня там всего одна кнопка для слабовидящих

**Comment by keha** [comment]
а, я уже забыл, что убрал второе
значит все верно

**Comment by itcrowd72** [comment]
У меня в хроме нормально работает, а в FF некорректно

**Comment by keha** [comment]
ну там на главной много чего понавешано, посмотри на другие странички в браузере

**Comment by itcrowd72** [comment]
У тебя есть FF? Попробуй этот сайт в нем

**Comment by itcrowd72** [comment]
Хм. Очистил полностью кэш браузера и всё заработало

**Comment by itcrowd72** [comment]
Ты бы поднял кнопку "обычная версия" наверх, а то люди будут искать как вернуться обратно...

**Comment by itcrowd72** [comment]
А эту проблему с выравниванием картинок я решил, обнову выложу в конце дня

**Comment by keha** [comment]
проблем не нашел в своем огнелисе редкооткрываемом :)
заметил, что сначала выравнивание происходит по центру, а потом что-то переопределяет стиль...

**Comment by itcrowd72** [comment]
Ок, значит глюк с ФФ был только у меня. Он что-то хорошо закэшировал твой сайт)

**Comment by keha** [comment]
)

**Comment by itcrowd72** [comment]
Внес изменения. Пробуй

**Comment by keha** [comment]
чудненько, все работает :)
можно уже и на третьем сайте пробовать

**Comment by itcrowd72** [comment]
Давай, пробуй) Если там проблем не найдём, то сделаю очередной релиз кандидат на орге
