### ISSUE TITLE
visually_impaired_theme conflict with nivo slider

### ISSUE THREAD

**Issue by keha** [itcrowd72/visually_impaired_theme#9]
Hello!
На сайте https://красгимнастика.рф/ на стартовой странице не работает верхняя панель управления размером шрифта и цветностью и перекрывается панелью toolbar. На других страницах все работает и панель не перекрывает toolbar. На стартовой используется Nivo Slider, есть подозрение, что причина в нём

**Comment by itcrowd72** [comment]
Выключи кэширование, пожалуйста

**Comment by itcrowd72** [comment]
И покажи скриншоты

**Comment by keha** [comment]
готово
а скриншоты не нужны, под анонимом такое же поведение

**Comment by itcrowd72** [comment]
Да, какой-то конфликт с ниво слайдером. В консоли браузера ошибки

**Comment by itcrowd72** [comment]
Дай мне доступ еще раз на сайт

**Comment by keha** [comment]
велкам

**Comment by itcrowd72** [comment]
Я исправил. Мой косяк был, я в настройках темы ставил jQuery 1.4.4 и забыл убрать

**Comment by keha** [comment]
тогда получается в зависимости надо добавлять jquery update

**Comment by itcrowd72** [comment]
Не. Дело в ниво-слайдере. Если бы его не было, то и системный jQuery 1.4.4 прекрасно бы работал. А для твоего ниво-слайдера нужен jQuery 1.10

**Comment by itcrowd72** [comment]
Я когда диагностировал другой баг, изменил версию jQuery в целях проверки и забыл вернуть назад jQuery 1.10, вот ниво-слайдер и сломался и сломал следом панель для слабовидящих)

**Comment by keha** [comment]
ниво слайдер может вообще положить сайт, если выставить случайный показ слайдов :)

**Comment by itcrowd72** [comment]
Эта проблема решена, переходим к следующей
